apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-mspay
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
      - path: /ms-ingress
        backend:
          serviceName: ms-ingress-svc
          servicePort: 30004