apiVersion: v1
kind: Service
metadata:
  name: ms-payments-svc
  labels:
     app: ms-payments
spec:
  type: NodePort
  ports:
  - port: 8080
    nodePort: 30004
    protocol: TCP
  selector:
     app: ms-payments
